version: '3'

services:
  app:
    build: .
    container_name: mysql-binlog-kafka
    environment:
      MYSQL_HOST: "host.docker.internal"
      MYSQL_PORT: "3306"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      KAFKA_TOPIC: "mysql-binlog-topic"
    restart: unless-stopped
    volumes:
      - $HOME/mysql-binlog-kafka-data/hostip:/app/hostip
    networks:
      - kafka_kafka-net

networks:
  kafka_kafka-net:
    external: true
